mod codex;
mod models;

use std::sync::Mutex;
use chrono::{DateTime, Datelike, Duration, Local};
use models::ProviderSnapshot;
use tauri::{menu::{CheckMenuItem, Menu, MenuItem, PredefinedMenuItem, Submenu}, tray::TrayIconBuilder, AppHandle, Manager};

struct AppState { client: reqwest::Client, snapshot: Mutex<Option<ProviderSnapshot>>, detailed: Mutex<bool> }

fn clock(value: Option<&str>) -> String { value.and_then(|v| DateTime::parse_from_rfc3339(v).ok()).map(|v| v.with_timezone(&Local).format("%H:%M").to_string()).unwrap_or_else(|| "--".into()) }
fn reset_label(value: Option<&str>) -> String { let Some(reset) = value.and_then(|v| DateTime::parse_from_rfc3339(v).ok()).map(|v| v.with_timezone(&Local)) else { return "--".into() }; if reset.signed_duration_since(Local::now()) < Duration::hours(24) { reset.format("%H:%M").to_string() } else { ["周一","周二","周三","周四","周五","周六","周日"][reset.weekday().num_days_from_monday() as usize].into() } }
fn summary(snapshot: Option<&ProviderSnapshot>) -> String { let Some(s) = snapshot.filter(|s| s.status == "ok") else { return "week -- · -- · --".into() }; let percent = s.weekly_window.as_ref().map(|w| format!("{:.0}%", w.remaining_percent)).unwrap_or_else(|| "--".into()); let reset = reset_label(s.weekly_window.as_ref().and_then(|w| w.resets_at.as_deref())); let credits = s.reset_credits.map(|n| format!("{n}次")).unwrap_or_else(|| "--".into()); format!("week {percent} · {reset} · {credits}") }
fn refresh(app: &AppHandle) { let app = app.clone(); tauri::async_runtime::spawn(async move { let state = app.state::<AppState>(); let next = codex::fetch_snapshot(&state.client).await; *state.snapshot.lock().unwrap() = Some(next); update(&app); }); }
fn update(app: &AppHandle) { let state = app.state::<AppState>(); let snapshot = state.snapshot.lock().unwrap().clone(); let detailed = *state.detailed.lock().unwrap(); let tray = app.tray_by_id("main").unwrap(); let _ = tray.set_title(if detailed { Some(summary(snapshot.as_ref())) } else { None::<String> }); let refresh_item = MenuItem::with_id(app,"refresh","立即刷新",true,None::<&str>).unwrap(); let detail = CheckMenuItem::with_id(app,"detailed","详细",true,detailed,None::<&str>).unwrap(); let icon = CheckMenuItem::with_id(app,"icon","仅图标",true,!detailed,None::<&str>).unwrap(); let modes = Submenu::with_items(app,"菜单栏显示方式",true,&[&detail,&icon]).unwrap(); let quit = MenuItem::with_id(app,"quit","退出",true,None::<&str>).unwrap(); let info = MenuItem::with_id(app,"info",summary(snapshot.as_ref()),false,None::<&str>).unwrap(); let menu = Menu::with_items(app,&[&info,&PredefinedMenuItem::separator(app).unwrap(),&refresh_item,&modes,&PredefinedMenuItem::separator(app).unwrap(),&quit]).unwrap(); let _ = tray.set_menu(Some(menu)); }
fn main() { tauri::Builder::default().setup(|app| { app.set_activation_policy(tauri::ActivationPolicy::Accessory); let client = reqwest::Client::builder().timeout(std::time::Duration::from_secs(12)).user_agent("CodexBar/0.1").build()?; app.manage(AppState { client, snapshot: Mutex::new(None), detailed: Mutex::new(false) }); let mut tray = TrayIconBuilder::with_id("main").tooltip("Codex Bar"); if let Some(icon) = app.default_window_icon() { tray = tray.icon(icon.clone()); } tray.on_menu_event(|app,event| match event.id.as_ref() { "refresh" => refresh(app), "detailed" => { *app.state::<AppState>().detailed.lock().unwrap() = true; update(app); }, "icon" => { *app.state::<AppState>().detailed.lock().unwrap() = false; update(app); }, "quit" => app.exit(0), _ => {} }).build(app)?; update(app.handle()); refresh(app.handle()); Ok(()) }).run(tauri::generate_context!()).expect("failed to run Codex Bar"); }
